### ISSUE TITLE
[Idea] Add ability to make things like fonts configurable

### ISSUE THREAD

**Issue by hktouw** [open-truss/open-truss#107]
Some folks work better with different font sets (e.g. OpenDyslexic). It would be great if OT can make it easy to swap fonts.

**Comment by kmcq** [comment]
I'm not sure we need anything new to make supporting this easy. We already support this by either the host application setting font CSS globally or by individual components having a prop that changes styles. What do you think? Are those easy and configurable enough?

**Comment by hktouw** [comment]
That makes sense to me! It seems like something that should be delegated to the host application like you're saying 👍

**Comment by kmcq** [comment]
Sweet yea! We can always add an API for it later, but this is a good place to start. I'll close this out
