### ISSUE TITLE
Style State Management Demo page

### ISSUE THREAD

**Issue by fionaochs** [open-truss/open-truss#143]
Part of the efforts for https://github.com/open-truss/open-truss/pull/114

Currently
![Image](https://github.com/open-truss/open-truss/assets/55855284/080ea52b-93d3-406a-8ffe-46261e28e88e)

**Comment by fionaochs** [comment]
Current state


![Image](https://github.com/open-truss/open-truss/assets/55855284/e708977a-8c19-4a77-8768-456df7ebbe7c)

**Comment by jonmagic** [comment]
Closing as complete
