### ISSUE TITLE
[Call To Action] Need your npm handle to add you to open-truss org on npm

### ISSUE THREAD

**Issue by hktouw** [open-truss/open-truss#15]
@open-truss/engineers I created this Open Truss npm org for us to use for publishing packages to. When you have a moment please create accounts on npm, enable 2fa since this is required for package publishing, and post your npm username in this issue so I can add you to the org.

**Comment by jonmagic** [comment]
I'm `jonmagic` on npm.

**Comment by kre64** [comment]
`kre64` on npm

**Comment by hktouw** [comment]
@open-truss/engineers going to close this out for now, but if folks want to join the npm org, feel free to reach out.
