### ISSUE TITLE
Support ability to pass in variables into workflows

### ISSUE THREAD

**Issue by hktouw** [open-truss/open-truss#170]
Currently there is no way to pass in data into a workflow. Data in the workflow needs to be hardcoded into the workflow config or fetched by data provider components. We'll want to come up with an elegant way to do this. Perhaps we can expose a new parameter in `RenderConfig` called `signals` that the caller can supply. We then make the signals available to components in the engine.

/cc @open-truss/engineers for your thoughts on this
/cc @kmcq @pourash-b as you things you are working on may need this functionality

**Comment by kmcq** [comment]
@hktouw yes! This will really help.

A RenderConfig param makes sense to me 👍 I was also thinking that it could be cool to have a config annotation that populates a signal from a query param. That would just be a helper around your idea though probably so let's do yours first.
