### ISSUE TITLE
[Task] Build a component/workflow/rendering playground

### ISSUE THREAD

**Issue by jonmagic** [open-truss/open-truss#32]
This playground will make it easier and faster for us to iterate on the:

1. Workflow spec
2. Components
3. Rendering engine

**Comment by hktouw** [comment]
We shipped a simple, yet function version of a playground. https://github.com/open-truss/open-truss/pull/48. This should serve as a good base as we build out the rendering engine and iterate on components. 

@kmcq @jonmagic There is some work to be done to ship a fully functioning version of the rendering engine with zod types. Do you think that should be in a follow up issue or a part of this one?

**Comment by kmcq** [comment]
I'm currently working faster and more chaotic than an issue, but I'll be slowing down soon and can write up what is in my head that I don't get to so that it's somewhere more durable

**Comment by kmcq** [comment]
Okay it's time for me to slow down a bit. I think that the following recent PRs wrap up this task:

- https://github.com/open-truss/open-truss/pull/64
- #76 
- #77

We now have a zod-powered way to construct and view configs in real time! I'll write up another issue for what else we could do in this space.
